export const ENV = {
  BASE_URL: process.env.BASE_URL as string,
  PREFERRED_CHAIN_ID: Number(process.env.PREFERRED_CHAIN_ID),
  ALCHEMY_API_KEY: process.env.ALCHEMY_API_KEY as string,
  BIMKON_EYES_ADDRESS: process.env.BIMKON_EYES_ADDRESS as string,
  SIGNATURE_CHECKER_ADDRESS: process.env.SIGNATURE_CHECKER_ADDRESS as string,
  SPREADSHEET_CLIENT_EMAIL: process.env.SPREADSHEET_CLIENT_EMAIL as string,
  SPREADSHEET_PRIVATE_KEY: process.env.SPREADSHEET_PRIVATE_KEY as string,
  SPREADSHEET_SUBSCRIPTIONS_ID: process.env.SPREADSHEET_SUBSCRIPTIONS_ID as string,
  SPREADSHEET_PRESALE_REQUESTS_ID: process.env.SPREADSHEET_PRESALE_REQUESTS_ID as string,
  SPREADSHEET_PRESALE_WHITELIST_ID: process.env.SPREADSHEET_PRESALE_WHITELIST_ID as string,
  SPREADSHEET_AIRDROP_REQUESTS_ID: process.env.SPREADSHEET_AIRDROP_REQUESTS_ID as string,
  SPREADSHEET_AIRDROP_WHITELIST_ID: process.env.SPREADSHEET_AIRDROP_WHITELIST_ID as string,
};
