export const ENVIRONMENT = {
  BASE_URL: process.env.BASE_URL,
  PREFERRED_CHAIN_ID: process.env.PREFERRED_CHAIN_ID,
  ALCHEMY_API_KEY: process.env.ALCHEMY_API_KEY,
  BIMKON_EYES_ADDRESS: process.env.BIMKON_EYES_ADDRESS,
  SIGNATURE_CHECKER_ADDRESS: process.env.SIGNATURE_CHECKER_ADDRESS,
  SPREADSHEET_CLIENT_EMAIL: process.env.SPREADSHEET_CLIENT_EMAIL,
  SPREADSHEET_PRIVATE_KEY: process.env.SPREADSHEET_PRIVATE_KEY,
  SPREADSHEET_SUBSCRIPTIONS_ID: process.env.SPREADSHEET_SUBSCRIPTIONS_ID,
  SPREADSHEET_PRESALE_REQUESTS_ID: process.env.SPREADSHEET_PRESALE_REQUESTS_ID,
  SPREADSHEET_PRESALE_WHITELIST_ID: process.env.SPREADSHEET_PRESALE_WHITELIST_ID,
  SPREADSHEET_AIRDROP_REQUESTS_ID: process.env.SPREADSHEET_AIRDROP_REQUESTS_ID,
  SPREADSHEET_AIRDROP_WHITELIST_ID: process.env.SPREADSHEET_AIRDROP_WHITELIST_ID,
};
